# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95aca1f19b7be0fe12b0c786afeff7e22f307b5c46d324c833be3437468082ded07488cd64031f3d6aa9c259ff932d83c1a15138976e02d712d1f433f446943

test:
  secret_key_base: 3b129ee8f8ae50bac3220fa16fe911ce2a9a3fcbc5ecbd2dc0b022656e63dab897433fe1d92774b3cc3e2a35ee2822ff251aba9e983359864e8f3d6d903d417c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
